version: '3.8'

services:
  # AI Cybersecurity API
  api:
    build: .
    container_name: ai-cybersecurity-api-prod
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=api/app.py
      - PYTHONPATH=/app
    volumes:
      - ./models:/app/models:ro
      - ./data:/app/data:ro
      - logs:/app/logs
    networks:
      - cybersecurity-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'

  # React Dashboard
  frontend:
    build: ./frontend/cybersecurity-dashboard
    container_name: ai-cybersecurity-dashboard-prod
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5001
    depends_on:
      - api
    networks:
      - cybersecurity-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: ai-cybersecurity-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - api
      - frontend
    networks:
      - cybersecurity-network
    restart: always

networks:
  cybersecurity-network:
    driver: bridge

volumes:
  logs:
    driver: local
