apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-cybersecurity-tool
  labels:
    app: ai-cybersecurity-tool
    version: v1.0.0
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ai-cybersecurity-tool
  template:
    metadata:
      labels:
        app: ai-cybersecurity-tool
        version: v1.0.0
    spec:
      containers:
      - name: api
        image: ai-cybersecurity-tool:latest
        ports:
        - containerPort: 5001
          name: api
        - containerPort: 9090
          name: metrics
        env:
        - name: FLASK_ENV
          value: "production"
        - name: API_HOST
          value: "0.0.0.0"
        - name: API_PORT
          value: "5001"
        - name: DATABASE_URL
          value: "sqlite:///data/threats.db"
        - name: LOG_LEVEL
          value: "INFO"
        - name: METRICS_ENABLED
          value: "True"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
        - name: logs-volume
          mountPath: /app/logs
        - name: models-volume
          mountPath: /app/models
        livenessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: ai-cybersecurity-data
      - name: logs-volume
        persistentVolumeClaim:
          claimName: ai-cybersecurity-logs
      - name: models-volume
        persistentVolumeClaim:
          claimName: ai-cybersecurity-models
      securityContext:
        fsGroup: 1000
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: ai-cybersecurity-tool-service
  labels:
    app: ai-cybersecurity-tool
spec:
  selector:
    app: ai-cybersecurity-tool
  ports:
  - name: api
    port: 80
    targetPort: 5001
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-cybersecurity-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: fast-ssd
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-cybersecurity-logs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-cybersecurity-models
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: fast-ssd
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ai-cybersecurity-tool-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ai-cybersecurity-tool
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
